//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop_AudioAllocation
    {
        public int Id { get; set; }
        public Nullable<int> CropId { get; set; }
        public Nullable<int> LangId { get; set; }
        public string FieldType { get; set; }
        public Nullable<int> AudioId { get; set; }
    }
}
