//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropSteps_Material
    {
        public int Id { get; set; }
        public int Step_Id { get; set; }
        public string Material_Name { get; set; }
        public string Material_Transaction { get; set; }
        public Nullable<decimal> Per_Decimal_Price { get; set; }
        public string Quantity { get; set; }
        public string Image_Path { get; set; }
        public string Audio_Path { get; set; }
    
        public virtual Cultivation_Steps Cultivation_Steps { get; set; }
    }
}
