//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropStep_VideoAllocation
    {
        public int Id { get; set; }
        public Nullable<int> StepId { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ActiveOn { get; set; }
        public Nullable<System.DateTime> ActiveBy { get; set; }
        public string Active { get; set; }
    }
}
