//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultivation_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cultivation_History()
        {
            this.CropCultivation_History = new HashSet<CropCultivation_History>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public Nullable<float> Total_Production { get; set; }
        public Nullable<float> Cost_Per_Kg { get; set; }
        public Nullable<float> LandArea { get; set; }
        public Nullable<float> Total_Cost_of_Cultivation { get; set; }
        public Nullable<int> CropId { get; set; }
        public string LandType { get; set; }
        public Nullable<int> Total_kg { get; set; }
        public Nullable<float> Total_Profit { get; set; }
        public Nullable<System.Guid> Cultivation_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ActiveBy { get; set; }
        public Nullable<System.DateTime> ActiveOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CropCultivation_History> CropCultivation_History { get; set; }
    }
}
