//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveStock_StepMaterial
    {
        public int Id { get; set; }
        public string LiveMaterialName { get; set; }
        public string LiveMaterialDesc { get; set; }
        public Nullable<int> LiveStock_StepId { get; set; }
        public string TitleAudioURL { get; set; }
        public string DescriptionAudioURL { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Cost { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ActiveBy { get; set; }
        public Nullable<System.DateTime> ActiveOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Category { get; set; }
        public string Quantity_measured { get; set; }
        public string Cost_measured { get; set; }
    
        public virtual LiveStock_Steps LiveStock_Steps { get; set; }
    }
}
