//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveStock_BreedCategory
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> BreedId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Units { get; set; }
        public Nullable<int> Quanitity { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ActiveBy { get; set; }
        public Nullable<System.DateTime> ActiveOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Category { get; set; }
    
        public virtual LiveStockBreed LiveStockBreed { get; set; }
    }
}
