//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveStock_Steps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LiveStock_Steps()
        {
            this.LiveStock_StepMaterial = new HashSet<LiveStock_StepMaterial>();
        }
    
        public int Id { get; set; }
        public string StepName { get; set; }
        public string StepDescription { get; set; }
        public Nullable<int> LiveStockId { get; set; }
        public string ImageURL { get; set; }
        public string StepAudioTitleURL { get; set; }
        public string StepAudioDesURL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ActiveBy { get; set; }
        public Nullable<System.DateTime> ActiveOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public string AliesName { get; set; }
    
        public virtual LiveStock LiveStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiveStock_StepMaterial> LiveStock_StepMaterial { get; set; }
        public virtual ICollection<LiveStock_StepMaterial> Adult { get; set; }
        public virtual ICollection<LiveStock_StepMaterial> Child { get; set; }
    }
}
