//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNeeded_History
    {
        public int Id { get; set; }
        public Nullable<int> StepId { get; set; }
        public string MaterialName { get; set; }
        public string MaterialTransaction { get; set; }
        public Nullable<int> PerDecimalPrice { get; set; }
        public string Quantity { get; set; }
        public Nullable<bool> MaterialUsed { get; set; }
        public Nullable<bool> PriceUpdated { get; set; }
        public string ImagePath { get; set; }
        public string ImgPathLocal { get; set; }
        public string AudioPath { get; set; }
        public string AudioPathLocal { get; set; }
        public Nullable<int> CultivationStepId { get; set; }
        public Nullable<System.Guid> CultivationUID { get; set; }
    
        public virtual CultivationStep_History CultivationStep_History { get; set; }
    }
}
