//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaContent
    {
        public int Id { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public string MediaType { get; set; }
        public string MediaURL { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> FileSize { get; set; }
    }
}
