//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedAudio
    {
        public int Id { get; set; }
        public string PredefinedText { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> LangCode { get; set; }
    }
}
