//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrickleUpEntities : DbContext
    {
        public TrickleUpEntities()
            : base("name=TrickleUpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MediaContent> MediaContents { get; set; }
        public virtual DbSet<BulkUploadRef> BulkUploadRefs { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<VillageContact> VillageContacts { get; set; }
        public virtual DbSet<FeedBackQuestion> FeedBackQuestions { get; set; }
        public virtual DbSet<UserFeedback> UserFeedbacks { get; set; }
        public virtual DbSet<CropSteps_Material> CropSteps_Material { get; set; }
        public virtual DbSet<PredefinedAudio> PredefinedAudios { get; set; }
        public virtual DbSet<Crop_AudioAllocation> Crop_AudioAllocation { get; set; }
        public virtual DbSet<CropMaterial_AudioAllocation> CropMaterial_AudioAllocation { get; set; }
        public virtual DbSet<CropStepAudio_Allocation> CropStepAudio_Allocation { get; set; }
        public virtual DbSet<Tbl_ExceptionLogging> Tbl_ExceptionLogging { get; set; }
        public virtual DbSet<Cultivation_Steps> Cultivation_Steps { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<MasterPassword> MasterPasswords { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
        public virtual DbSet<UserFCMToken> UserFCMTokens { get; set; }
        public virtual DbSet<CurrencyStock> CurrencyStocks { get; set; }
        public virtual DbSet<MoneyManager> MoneyManagers { get; set; }
        public virtual DbSet<PushNotification> PushNotifications { get; set; }
        public virtual DbSet<CropCultivation_History> CropCultivation_History { get; set; }
        public virtual DbSet<Cultivation_History> Cultivation_History { get; set; }
        public virtual DbSet<CultivationStep_History> CultivationStep_History { get; set; }
        public virtual DbSet<MaterialNeeded_History> MaterialNeeded_History { get; set; }
        public virtual DbSet<Grampanchayat> Grampanchayats { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Audio> Audios { get; set; }
        public virtual DbSet<Crop_VideoAllocation> Crop_VideoAllocation { get; set; }
        public virtual DbSet<CropStep_VideoAllocation> CropStep_VideoAllocation { get; set; }
        public virtual DbSet<CropStepMaterial_VideoAllocation> CropStepMaterial_VideoAllocation { get; set; }
        public virtual DbSet<LiveStockBreed> LiveStockBreeds { get; set; }
        public virtual DbSet<LiveStock_StepMaterial> LiveStock_StepMaterial { get; set; }
        public virtual DbSet<LiveStock> LiveStocks { get; set; }
        public virtual DbSet<LiveStock_AudioAllocation> LiveStock_AudioAllocation { get; set; }
        public virtual DbSet<LiveStock_BreedCategory> LiveStock_BreedCategory { get; set; }
        public virtual DbSet<LiveStock_BreedCategory_AudioAllocation> LiveStock_BreedCategory_AudioAllocation { get; set; }
        public virtual DbSet<LiveStockBreed_AudioAllocation> LiveStockBreed_AudioAllocation { get; set; }
        public virtual DbSet<LiveStock_Steps_AudioAllocation> LiveStock_Steps_AudioAllocation { get; set; }
        public virtual DbSet<LiveStock_StepsMaterial_AudioAllocation> LiveStock_StepsMaterial_AudioAllocation { get; set; }
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<LiveStock_Steps> LiveStock_Steps { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
