//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_Oriya {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Oriya() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrickleUpPortal.Resources.Lang_Oriya", typeof(Lang_Oriya).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE-NA.
        /// </summary>
        internal static string DDO_NA {
            get {
                return ResourceManager.GetString("DDO-NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMN-NA.
        /// </summary>
        internal static string EMN_NA {
            get {
                return ResourceManager.GetString("EMN-NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amrutjal.
        /// </summary>
        internal static string ଅମୃତଜାଲ {
            get {
                return ResourceManager.GetString("ଅମୃତଜାଲ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amrutjal Solution.
        /// </summary>
        internal static string ଅମୃତଜାଲ_ସୋଲୁସନ {
            get {
                return ResourceManager.GetString("ଅମୃତଜାଲ ସୋଲୁସନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agneyastra with Water.
        /// </summary>
        internal static string ଆଗ୍ନେୟାସ୍ତ୍ର_ବିଠ_ୱାଟର {
            get {
                return ResourceManager.GetString("ଆଗ୍ନେୟାସ୍ତ୍ର ବିଠ ୱାଟର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Organic Pesticides and Fertilizers.
        /// </summary>
        internal static string ଉସେ__ଅ__ଅର୍ଗାନିକ__ପେସ୍ଟିସିଦେଶ__ଆଣ୍ଡ__ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ {
            get {
                return ResourceManager.GetString("ଉସେ  ଅ  ଅର୍ଗାନିକ  ପେସ୍ଟିସିଦେଶ  ଆଣ୍ଡ  ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Organic Pesticides and Fertilizers after 40 days of seed filling, Spray Amrutjal two times (in 2 -3 days interval) - Amrutjal can not be stored, it needs to be sprayed just after the preparation..
        /// </summary>
        internal static string ଉସେ__ଅର୍ଗାନିକ__ପେସ୍ଟିସିଦେଶ___ଆଣ୍ଡ__ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ__ଅଃଫ୍ଟୱେର__୪୦__ଦେଶ__ଅ__ସେଏଡ଼__ଫିଲଳିଙ୍ଗ__ସ୍ପ୍ରେ__ଅମୃତଜାଲ__ତ୍ୱ__ଟିମଏସ___ଇଂ__୨____୩__ଦେଶ__ଇଣ୍ଟେରବଲ_____ଅମୃତଜାଲ__ଚାଁ__ନୋଟ__ବେ__ସ୍ଟ୍ରେଡ଼___ଇଟା__ନୀଡ଼ସ__ତୋ__ବେ__ସ୍ପରଏଡ଼__ଜୁସତ__ଅଃଫ୍ଟୱେର__ଥେ__ପରିପାରସନ_ {
            get {
                return ResourceManager.GetString("ଉସେ  ଅର୍ଗାନିକ  ପେସ୍ଟିସିଦେଶ   ଆଣ୍ଡ  ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ  ଅଃଫ୍ଟୱେର  ୪୦  ଦେଶ  ଅ  ସେଏଡ଼  " +
                        "ଫିଲଳିଙ୍ଗ, ସ୍ପ୍ରେ  ଅମୃତଜାଲ  ତ୍ୱ  ଟିମଏସ  (ଇଂ  ୨  - ୩  ଦେଶ  ଇଣ୍ଟେରବଲ ) - ଅମୃତଜାଲ  ଚ" +
                        "ାଁ  ନୋଟ  ବେ  ସ୍ଟ୍ରେଡ଼ , ଇଟା  ନୀଡ଼ସ  ତୋ  ବେ  ସ୍ପରଏଡ଼  ଜୁସତ  ଅଃଫ୍ଟୱେର  ଥେ  ପରିପାରସ" +
                        "ନ.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Organic Pesticides and Fertilizers after 50 days of seed filling, Spray Handikhata Solution or Agneyastra Solution and spray Amrutjal Solution - one time.
        /// </summary>
        internal static string ଉସେ__ଅର୍ଗାନିକ__ପେସ୍ଟିସିଦେଶ__ଆଣ୍ଡ__ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ__ଅଃଫ୍ଟୱେର__୫୦__ଦେଶ__ଅ__ସେଏଡ଼__ଫିଲଳିଙ୍ଗ__ସ୍ପ୍ରେ__ହାନ୍ଡିଖାତା__ସୋଲୁସନ__ଡ__ଆଗ୍ନେୟାସ୍ତ୍ର__ସୋଲୁସନ__ଆଣ୍ଡ__ସ୍ପ୍ରେ__ଅମୃତଜାଲ__ସୋଲୁସନ____ଅଣେ__ର୍ଟମେ {
            get {
                return ResourceManager.GetString("ଉସେ  ଅର୍ଗାନିକ  ପେସ୍ଟିସିଦେଶ  ଆଣ୍ଡ  ଫର୍ଟିଲାୱୀଜ଼ଏର୍ସ  ଅଃଫ୍ଟୱେର  ୫୦  ଦେଶ  ଅ  ସେଏଡ଼  ଫ" +
                        "ିଲଳିଙ୍ଗ, ସ୍ପ୍ରେ  ହାନ୍ଡିଖାତା  ସୋଲୁସନ  ଡ  ଆଗ୍ନେୟାସ୍ତ୍ର  ସୋଲୁସନ  ଆଣ୍ଡ  ସ୍ପ୍ରେ  ଅମୃତ" +
                        "ଜାଲ  ସୋଲୁସନ  - ଅଣେ  ର୍ଟମେ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bowl/Container.
        /// </summary>
        internal static string ଏ_ବଉଳ_କଂଟିନଏର {
            get {
                return ResourceManager.GetString("ଏ ବଉଳ/କଂଟିନଏର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion.
        /// </summary>
        internal static string ଓନିଅଁ {
            get {
                return ResourceManager.GetString("ଓନିଅଁ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauliflower.
        /// </summary>
        internal static string ଚାଉଳିଫ୍ଲୋବେର {
            get {
                return ResourceManager.GetString("ଚାଉଳିଫ୍ଲୋବେର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilli.
        /// </summary>
        internal static string ଚି଼ଲ୍ଲୀ {
            get {
                return ResourceManager.GetString("ଚି଼ଲ୍ଲୀ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumber.
        /// </summary>
        internal static string ଚୁଚୁମ୍ବର {
            get {
                return ResourceManager.GetString("ଚୁଚୁମ୍ବର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cow Urine Solution.
        /// </summary>
        internal static string ଚୋବ_ୟୁରିନେ_ସୋଲୁସନ {
            get {
                return ResourceManager.GetString("ଚୋବ ୟୁରିନେ ସୋଲୁସନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabbage.
        /// </summary>
        internal static string ଛାଵଗେ {
            get {
                return ResourceManager.GetString("ଛାଵଗେ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        internal static string ଟମାଟୋ {
            get {
                return ResourceManager.GetString("ଟମାଟୋ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Agneyastra with Water.
        /// </summary>
        internal static string ଡ_ଆଗ୍ନେୟାସ୍ତ୍ର_ବିଠ_ୱାଟର {
            get {
                return ResourceManager.GetString("ଡ ଆଗ୍ନେୟାସ୍ତ୍ର ବିଠ ୱାଟର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Pranamrita.
        /// </summary>
        internal static string ଡ_ପ୍ରଂଅମୃତ {
            get {
                return ResourceManager.GetString("ଡ ପ୍ରଂଅମୃତ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neem Coated Urea (Incubated Urea) with Compost.
        /// </summary>
        internal static string ନିମ_ଚୋରେଟେଡ଼_ୟୁରିଆ__ଇଞ୍ଚୁବଟେଡ଼_ୟୁରିଆ__ବିଠ_କମ୍ପୋଷ୍ଟ {
            get {
                return ResourceManager.GetString("ନିମ ଚୋରେଟେଡ଼ ୟୁରିଆ (ଇଞ୍ଚୁବଟେଡ଼ ୟୁରିଆ) ବିଠ କମ୍ପୋଷ୍ଟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neem Coated Urea (Incubated Urea) with Compost.
        /// </summary>
        internal static string ନିମ_ଚୋରେଟେଡ଼_ୟୁରିଆ__ଇଞ୍ଚୁବଟେଡ଼_ୟୁରିଆ__ବିଠ_କମ୍ପୋଷ୍ଟ1 {
            get {
                return ResourceManager.GetString("ନିମ ଚୋରେଟେଡ଼ ୟୁରିଆ (ଇଞ୍ଚୁବଟେଡ଼ ୟୁରିଆ) ବିଠ କମ୍ପୋଷ୍ଟ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pits 3x3.
        /// </summary>
        internal static string ନୁଁମ୍ବର_ଅ_ପିସ୍ତା_୩କ୍ସ୩ {
            get {
                return ResourceManager.GetString("ନୁଁମ୍ବର ଅ ପିସ୍ତା ୩କ୍ସ୩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation of Pit, Seed and Nutrition Requirement.
        /// </summary>
        internal static string ପରିପାରସନ__ଅ__ପିତ___ସେଏଡ଼__ଆଣ୍ଡ__ନୁଁଟ୍ରିସନ__ରେକଇଁରେମେଣ୍ଟ {
            get {
                return ResourceManager.GetString("ପରିପାରସନ  ଅ  ପିତ , ସେଏଡ଼  ଆଣ୍ଡ  ନୁଁଟ୍ରିସନ  ରେକଇଁରେମେଣ୍ଟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plouging of Land.
        /// </summary>
        internal static string ପଲୋଉଗିଙ୍ଗ_ଅ_ଲଣ୍ଡ {
            get {
                return ResourceManager.GetString("ପଲୋଉଗିଙ୍ଗ ଅ ଲଣ୍ଡ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plouging with Oxen.
        /// </summary>
        internal static string ପଲୋଉଗିଙ୍ଗ_ବିଠ_ଓସଏନ {
            get {
                return ResourceManager.GetString("ପଲୋଉଗିଙ୍ଗ ବିଠ ଓସଏନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plouging of Land 2-3 times for main field preparation.
        /// </summary>
        internal static string ପଲୋଉଘ__ଲଣ୍ଡ__୨__୩__ଟିମଏସ__ଫୋର__ମାଇଁ__ଫାଇଲଡ__ପରିପାରସନ {
            get {
                return ResourceManager.GetString("ପଲୋଉଘ  ଲଣ୍ଡ  ୨ -୩  ଟିମଏସ  ଫୋର  ମାଇଁ  ଫାଇଲଡ  ପରିପାରସନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        internal static string ପୁଂପକିନ {
            get {
                return ResourceManager.GetString("ପୁଂପକିନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put all seeds into a bowl of cold water and keep it for 15-20 hours. Seeds need to be dried in shadow on ginni bag. Seed priming needs to be done just one day before seed treatment and sowing in the pit..
        /// </summary>
        internal static string ପୁଟ__ଳ__ସୀଦଶ__ଈଂଟ__ଏ__ବଉଳ__ଅ__କଲଡ__ୱାଟର__ଆଣ୍ଡ__କେଇପ__ଇଟା__ଫୋର__୧୫__୨୦__ହୋଉଶ__ସୀଦଶ__ନୀଡ଼__ତୋ__ବେ__ଦ୍ରିଏଡ଼__ଇଂ__ଶଦଉ__ଓଂ__ଗଈଂନି__ବଗ___ସେଏଡ଼__ପରିମିଙ୍ଗ__ନୀଡ଼ସ__ତୋ__ବେ__ଦନେ__ଜୁସତ__ଅଣେ__ଦେ__ବେଫୋରେ__ସେଏଡ଼__ଟ୍ରେରେଟମେଣ୍ଟ__ଆଣ୍ଡ__ସ୍ଵୟଂ__ଇଂ__ଥେ__ପିତ_ {
            get {
                return ResourceManager.GetString("ପୁଟ  ଳ  ସୀଦଶ  ଈଂଟ  ଏ  ବଉଳ  ଅ  କଲଡ  ୱାଟର  ଆଣ୍ଡ  କେଇପ  ଇଟା  ଫୋର  ୧୫ -୨୦  ହୋଉଶ. ସୀଦଶ" +
                        "  ନୀଡ଼  ତୋ  ବେ  ଦ୍ରିଏଡ଼  ଇଂ  ଶଦଉ  ଓଂ  ଗଈଂନି  ବଗ . ସେଏଡ଼  ପରିମିଙ୍ଗ  ନୀଡ଼ସ  ତୋ  ବେ" +
                        "  ଦନେ  ଜୁସତ  ଅଣେ  ଦେ  ବେଫୋରେ  ସେଏଡ଼  ଟ୍ରେରେଟମେଣ୍ଟ  ଆଣ୍ଡ  ସ୍ଵୟଂ  ଇଂ  ଥେ  ପିତ.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Weeding and Hoeing after 10 days of Seed Filling in the Pit. Put Vermicompost or Pranamrita in each pit. Spray Handikhata after 1-2 days of putting Vermicompost. Spray Agneyastra, if needed.
        /// </summary>
        internal static string ଫିରସ୍ତ__ୱେଇଡିଙ୍ଗ__ଆଣ୍ଡ__ହୋୱେଇଙ୍ଗ__ଅଃଫ୍ଟୱେର__୧୦_ଦେଶ__ଅ__ସେଏଡ଼__ଫିଲଳିଙ୍ଗ__ଇଂ_ଥେ__ପିତ__ପୁଟ__ବେରଂମିକମ୍ପସ୍ଟି__ଡ__ପ୍ରଂଅମୃତ__ଇଂ__ୱେଟ__ପିତ__ସ୍ପ୍ରେ__ହାନ୍ଡିଖାତା__ଅଃଫ୍ଟୱେର__୧___୨__ଦେଶ__ଅ__ପୁଟ୍ଟୀଙ୍ଗ__ବେରଂମିକମ୍ପସ୍ଟି__ସ୍ପ୍ରେ__ଆଗ୍ନେୟାସ୍ତ୍ର__ଇଫ__ନୀଡ଼ଏଡ଼ {
            get {
                return ResourceManager.GetString("ଫିରସ୍ତ  ୱେଇଡିଙ୍ଗ  ଆଣ୍ଡ  ହୋୱେଇଙ୍ଗ  ଅଃଫ୍ଟୱେର  ୧୦ ଦେଶ  ଅ  ସେଏଡ଼  ଫିଲଳିଙ୍ଗ  ଇଂ ଥେ  ପି" +
                        "ତ. ପୁଟ  ବେରଂମିକମ୍ପସ୍ଟି  ଡ  ପ୍ରଂଅମୃତ  ଇଂ  ୱେଟ  ପିତ. ସ୍ପ୍ରେ  ହାନ୍ଡିଖାତା  ଅଃଫ୍ଟୱେର " +
                        " ୧ - ୨  ଦେଶ  ଅ  ପୁଟ୍ଟୀଙ୍ଗ  ବେରଂମିକମ୍ପସ୍ଟି. ସ୍ପ୍ରେ  ଆଗ୍ନେୟାସ୍ତ୍ର, ଇଫ  ନୀଡ଼ଏଡ଼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Weeding and Hoeing.
        /// </summary>
        internal static string ଫିରସ୍ତ_ୱେଇଡିଙ୍ଗ_ଆଣ୍ଡ_ହୋୱେଇଙ୍ଗ {
            get {
                return ResourceManager.GetString("ଫିରସ୍ତ ୱେଇଡିଙ୍ଗ ଆଣ୍ଡ ହୋୱେଇଙ୍ଗ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brinjal.
        /// </summary>
        internal static string ବଋଂଜଳ {
            get {
                return ResourceManager.GetString("ବଋଂଜଳ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap seeds in cotton cloth and soak it, then dip it into cow urine and water Solution or Beejamrita Solution for 5 minutes. Then dry the soaked seeds in a shaded area upto 1-2 hours and sow in the pits..
        /// </summary>
        internal static string ବରପି__ସୀଦଶ__ଇଂ__ସର୍ତ୍ତନ__ସଲତ__ଆଣ୍ଡ__ଶାକ__ଇଟା__ଠେଁ__ଦୀପ__ଇଟା__ଈଂଟ__ଚୋବ__ୟୁରିନେ__ଆଣ୍ଡ__ୱାଟର__ସୋଲୁସନ__ଡ__ବୀଜମୃତ__ସୋଲୁସନ__ଫୋର__୫__ମିନୁତେଷୁ__ଠେଁ__ଦରୀ__ଥେ__ସାକେଡ଼__ସୀଦଶ__ଇଂ__ଏ__ଷଡ଼େଡ଼__ଆରେଏ__ଉପତ୍ୟ__୧__୨__ହୋଉଶ__ଆଣ୍ଡ__ସ୍ଵ__ଇଂ__ଥେ__ପିସ୍ତା_ {
            get {
                return ResourceManager.GetString("ବରପି  ସୀଦଶ  ଇଂ  ସର୍ତ୍ତନ  ସଲତ  ଆଣ୍ଡ  ଶାକ  ଇଟା, ଠେଁ  ଦୀପ  ଇଟା  ଈଂଟ  ଚୋବ  ୟୁରିନେ  ଆଣ" +
                        "୍ଡ  ୱାଟର  ସୋଲୁସନ  ଡ  ବୀଜମୃତ  ସୋଲୁସନ  ଫୋର  ୫  ମିନୁତେଷୁ. ଠେଁ  ଦରୀ  ଥେ  ସାକେଡ଼  ସୀଦଶ" +
                        "  ଇଂ  ଏ  ଷଡ଼େଡ଼  ଆରେଏ  ଉପତ୍ୟ  ୧ -୨  ହୋଉଶ  ଆଣ୍ଡ  ସ୍ଵ  ଇଂ  ଥେ  ପିସ୍ତା.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter Gourd.
        /// </summary>
        internal static string ବିତ୍ତ୍ଵେର_ଗୌରଡ଼ {
            get {
                return ResourceManager.GetString("ବିତ୍ତ୍ଵେର ଗୌରଡ଼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter Gourd Harvesting.
        /// </summary>
        internal static string ବିତ୍ତ୍ଵେର_ଗୌରଡ଼_ହରବେଶଟିଙ୍ଗ {
            get {
                return ResourceManager.GetString("ବିତ୍ତ୍ଵେର ଗୌରଡ଼ ହରବେଶଟିଙ୍ଗ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beejamrita Solution.
        /// </summary>
        internal static string ବୀଜମୃତ_ସୋଲୁସନ {
            get {
                return ResourceManager.GetString("ବୀଜମୃତ ସୋଲୁସନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermicompost.
        /// </summary>
        internal static string ବେରଂମିକମ୍ପସ୍ଟି {
            get {
                return ResourceManager.GetString("ବେରଂମିକମ୍ପସ୍ଟି", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermicompost.
        /// </summary>
        internal static string ବେରଂମିକମ୍ପସ୍ଟି1 {
            get {
                return ResourceManager.GetString("ବେରଂମିକମ୍ପସ୍ଟି1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macha or Stick.
        /// </summary>
        internal static string ମାଛ_ଡ_ସ୍ଟିସିକ {
            get {
                return ResourceManager.GetString("ମାଛ ଡ ସ୍ଟିସିକ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Beans.
        /// </summary>
        internal static string ଲଙ୍ଗ_ବେଆନ୍ସ {
            get {
                return ResourceManager.GetString("ଲଙ୍ଗ ବେଆନ୍ସ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady finger.
        /// </summary>
        internal static string ଲେଡି_ଫିଙ୍ଗର {
            get {
                return ResourceManager.GetString("ଲେଡି ଫିଙ୍ଗର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string ୱାଟର {
            get {
                return ResourceManager.GetString("ୱାଟର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radish.
        /// </summary>
        internal static string ଵାଦୀଶଃ {
            get {
                return ResourceManager.GetString("ଵାଦୀଶଃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between two pits should be 3 feet and spacing between two rows should be 3 feet. Put Hadri and Compost mix in each pit and Vermicompost. Put dried out 3 seeds in each pit.
        /// </summary>
        internal static string ସ୍ପଚିଙ୍ଗ__ବେତବୀନ__ତ୍ୱ__ପିସ୍ତା__ଷୌଲଡ଼__ବେ__୩__ଫେଡ__ଆଣ୍ଡ__ସ୍ପଚିଙ୍ଗ__ବେତବୀନ__ତ୍ୱ__ରୋବତ୍ସ__ଷୌଲଡ଼__ବେ__୩__ଫେଡ__ପୁଟ__ହ୍ୟାଦ୍ରି__ଆଣ୍ଡ__କମ୍ପୋଷ୍ଟ__ମିସ__ଇଂ__ୱେଟ__ପିତ__ଆଣ୍ଡ__ବେରଂମିକମ୍ପସ୍ଟି__ପୁଟ__ଦ୍ରିଏଡ଼__ଓଟ__୩__ସୀଦଶ__ଇଂ__ୱେଟ__ପିତ {
            get {
                return ResourceManager.GetString("ସ୍ପଚିଙ୍ଗ  ବେତବୀନ  ତ୍ୱ  ପିସ୍ତା  ଷୌଲଡ଼  ବେ  ୩  ଫେଡ  ଆଣ୍ଡ  ସ୍ପଚିଙ୍ଗ  ବେତବୀନ  ତ୍ୱ  ରୋ" +
                        "ବତ୍ସ  ଷୌଲଡ଼  ବେ  ୩  ଫେଡ. ପୁଟ  ହ୍ୟାଦ୍ରି  ଆଣ୍ଡ  କମ୍ପୋଷ୍ଟ  ମିସ  ଇଂ  ୱେଟ  ପିତ  ଆଣ୍ଡ " +
                        " ବେରଂମିକମ୍ପସ୍ଟି. ପୁଟ  ଦ୍ରିଏଡ଼  ଓଟ  ୩  ସୀଦଶ  ଇଂ  ୱେଟ  ପିତ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton Cloth.
        /// </summary>
        internal static string ସର୍ତ୍ତନ_ସଲତ {
            get {
                return ResourceManager.GetString("ସର୍ତ୍ତନ ସଲତ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds.
        /// </summary>
        internal static string ସୀଦଶ {
            get {
                return ResourceManager.GetString("ସୀଦଶ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds.
        /// </summary>
        internal static string ସୀଦଶ1 {
            get {
                return ResourceManager.GetString("ସୀଦଶ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Treatment.
        /// </summary>
        internal static string ସେଏଡ଼__ଟ୍ରେରେଟମେଣ୍ଟ {
            get {
                return ResourceManager.GetString("ସେଏଡ଼  ଟ୍ରେରେଟମେଣ୍ଟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Priming, Seed Treatment and Preparation of Pit, Seed and Nutrition requirement.
        /// </summary>
        internal static string ସେଏଡ଼_ପରିମିଙ୍ଗ__ସେଏଡ଼_ଟ୍ରେରେଟମେଣ୍ଟ_ଆଣ୍ଡ_ପରିପାରସନ_ଅ__ପିତ__ସେଏଡ଼__ଆଣ୍ଡ__ନୁଁଟ୍ରିସନ__ରେକଇଁରେମେଣ୍ଟ {
            get {
                return ResourceManager.GetString("ସେଏଡ଼ ପରିମିଙ୍ଗ, ସେଏଡ଼ ଟ୍ରେରେଟମେଣ୍ଟ ଆଣ୍ଡ ପରିପାରସନ ଅ  ପିତ, ସେଏଡ଼  ଆଣ୍ଡ  ନୁଁଟ୍ରିସନ  " +
                        "ରେକଇଁରେମେଣ୍ଟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Weeding and Hoeing.
        /// </summary>
        internal static string ସେକେଣ୍ଡ__ୱେଇଡିଙ୍ଗ__ଆଣ୍ଡ__ହୋୱେଇଙ୍ଗ {
            get {
                return ResourceManager.GetString("ସେକେଣ୍ଡ  ୱେଇଡିଙ୍ଗ  ଆଣ୍ଡ  ହୋୱେଇଙ୍ଗ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Weeding and Hoeing after 25 days of seed filling. Provide Muchha or Stick for support. Put Neem coated incubated Urea (with Compost). Spray Agneyastra.
        /// </summary>
        internal static string ସେକେଣ୍ଡ__ୱେଇଡିଙ୍ଗ__ଆଣ୍ଡ__ହୋୱେଇଙ୍ଗ__ଅଃଫ୍ଟୱେର__୨୫__ଦେଶ__ଅ__ସେଏଡ଼__ଫିଲଳିଙ୍ଗ__ପ୍ରୋଭିଡେ__ମଉଛ__ଡ__ସ୍ଟିସିକ__ଫୋର__ସପୋର୍ଟ__ପୁଟ__ନିମ__ଚୋରେଟେଡ଼__ଇଞ୍ଚୁବଟେଡ଼__ୟୁରିଆ___ବିଠ__କମ୍ପୋଷ୍ଟ____ସ୍ପ୍ରେ__ଆଗ୍ନେୟାସ୍ତ୍ର {
            get {
                return ResourceManager.GetString("ସେକେଣ୍ଡ  ୱେଇଡିଙ୍ଗ  ଆଣ୍ଡ  ହୋୱେଇଙ୍ଗ  ଅଃଫ୍ଟୱେର  ୨୫  ଦେଶ  ଅ  ସେଏଡ଼  ଫିଲଳିଙ୍ଗ. ପ୍ରୋଭିଡ" +
                        "େ  ମଉଛ  ଡ  ସ୍ଟିସିକ  ଫୋର  ସପୋର୍ଟ. ପୁଟ  ନିମ  ଚୋରେଟେଡ଼  ଇଞ୍ଚୁବଟେଡ଼  ୟୁରିଆ  (ବିଠ  କମ" +
                        "୍ପୋଷ୍ଟ ). ସ୍ପ୍ରେ  ଆଗ୍ନେୟାସ୍ତ୍ର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadri and Compost Mix.
        /// </summary>
        internal static string ହ୍ୟାଦ୍ରି_ଆଣ୍ଡ_କମ୍ପୋଷ୍ଟ_ମିସ {
            get {
                return ResourceManager.GetString("ହ୍ୟାଦ୍ରି ଆଣ୍ଡ କମ୍ପୋଷ୍ଟ ମିସ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handikhata with Water.
        /// </summary>
        internal static string ହାନ୍ଡିଖାତା_ବିଠ_ୱାଟର {
            get {
                return ResourceManager.GetString("ହାନ୍ଡିଖାତା ବିଠ ୱାଟର", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handikhata Solution.
        /// </summary>
        internal static string ହାନ୍ଡିଖାତା_ସୋଲୁସନ {
            get {
                return ResourceManager.GetString("ହାନ୍ଡିଖାତା ସୋଲୁସନ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handikhata Solution.
        /// </summary>
        internal static string ହାନ୍ଡିଖାତା_ସୋଲୁସନ1 {
            get {
                return ResourceManager.GetString("ହାନ୍ଡିଖାତା ସୋଲୁସନ1", resourceCulture);
            }
        }
    }
}
