//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrickleUpPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang_hindi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_hindi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrickleUpPortal.Resources.Lang_hindi", typeof(Lang_hindi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to करेला.
        /// </summary>
        public static string BitterGourd {
            get {
                return ResourceManager.GetString("BitterGourd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बैंगन.
        /// </summary>
        public static string Brinjal {
            get {
                return ResourceManager.GetString("Brinjal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गोभी.
        /// </summary>
        public static string Cabbage {
            get {
                return ResourceManager.GetString("Cabbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गोभी.
        /// </summary>
        public static string Cauliflower {
            get {
                return ResourceManager.GetString("Cauliflower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिर्च.
        /// </summary>
        public static string Chilli {
            get {
                return ResourceManager.GetString("Chilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खीरा.
        /// </summary>
        public static string Cucumber {
            get {
                return ResourceManager.GetString("Cucumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to भिन्डी.
        /// </summary>
        public static string Ladyfinger {
            get {
                return ResourceManager.GetString("Ladyfinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्याज.
        /// </summary>
        public static string Onion {
            get {
                return ResourceManager.GetString("Onion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कद्दू.
        /// </summary>
        public static string Pumpkin {
            get {
                return ResourceManager.GetString("Pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मूली.
        /// </summary>
        public static string Radish {
            get {
                return ResourceManager.GetString("Radish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टमाटर.
        /// </summary>
        public static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
    }
}
